# Generated by Django 5.2.15 on 2026-06-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complated', 'Complated')], max_length=100, null=True),
        ),
    ]
